<a href="https://colab.research.google.com/github/BartekNice31/machine_learning_bootcamp/blob/main/supervised/01_basics/02_cwiczenie_braki_danych.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### scikit-learn
Strona biblioteki: [https://scikit-learn.org](https://scikit-learn.org)  

Dokumentacja/User Guide: [https://scikit-learn.org/stable/user_guide.html](https://scikit-learn.org/stable/user_guide.html)

Podstawowa biblioteka do uczenia maszynowego w języku Python.

Aby zainstalować bibliotekę scikit-learn, użyj polecenia poniżej:
```
!pip install scikit-learn
```
Aby zaktualizować do najnowszej wersji bibliotekę scikit-learn, użyj polecenia poniżej:
```
!pip install --upgrade scikit-learn
```
Kurs stworzony w oparciu o wersję `0.22.1`

### Preprocessing danych:
1. [Import bibliotek](#0)
2. [Wygenerowanie danych](#1)
3. [Utworzenie kopii danych](#2)
4. [Zmiana typu danych i wstępna eksploracja](#3)
5. [LabelEncoder](#4)
6. [OneHotEncoder](#5)
7. [Pandas *get_dummies()*](#6)
8. [Standaryzacja - StandardScaler](#7)
9. [Przygotowanie danych do modelu](#8)



In [ ]:
!pip install --upgrade scikit-learn

In [ ]:
import numpy as np
import pandas as pd
import sklearn
from sklearn.preprocessing import LabelEncoder

sklearn.__version__

'1.8.0'

In [ ]:
data = {
    'size': ['XL', 'L', 'M', np.nan, 'M', 'M'],
    'color': ['red', 'green', 'blue', 'green', 'red', 'green'],
    'gender': ['female', 'male', np.nan, 'female', 'female', 'male'],
    'price': [199.0, 89.0, np.nan, 129.0, 79.0, 89.0],
    'weight': [500, 450, 300, np.nan, 410, np.nan],
    'bought': ['yes', 'no', 'yes', 'no', 'yes', 'no']
}

df_raw = pd.DataFrame(data=data)
df_raw

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue     NaN    NaN   300.0    yes
3  NaN  green  female  129.0     NaN     no
4    M    red  female   79.0   410.0    yes
5    M  green    male   89.0     NaN     no

In [ ]:
df=df_raw.copy()

# **Ważne- w oparciu o brak danych (uzupełnienie średnia lub mediana) wykonujemy te obliczenia na treningowych zbiorach!!!!**

In [ ]:
df

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue     NaN    NaN   300.0    yes
3  NaN  green  female  129.0     NaN     no
4    M    red  female   79.0   410.0    yes
5    M  green    male   89.0     NaN     no

In [ ]:
df.isna().sum()/len(df)

size      0.166667
color     0.000000
gender    0.166667
price     0.166667
weight    0.333333
bought    0.000000
dtype: float64

In [ ]:
df['size'].value_counts()

size
M     3
XL    1
L     1
Name: count, dtype: int64

In [ ]:
df['size'].mode()[0]

'M'

In [ ]:
df['size']=df['size'].fillna(df['size'].mode()[0])
df['gender']=df['gender'].fillna(df['gender'].mode()[0])

In [ ]:
df

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue  female    NaN   300.0    yes
3    M  green  female  129.0     NaN     no
4    M    red  female   79.0   410.0    yes
5    M  green    male   89.0     NaN     no

In [ ]:
df['price']=df['price'].fillna(df['price'].median())
df['weight']=df['weight'].fillna(df['weight'].median())

In [ ]:
[df['price'].mean(),df['price'].median()],[df['weight'].mean(),df['weight'].median()]

([np.float64(117.0), 89.0], [np.float64(415.0), 430.0])

In [ ]:
df,df.isna().sum().sum()==0

(  size  color  gender  price  weight bought
 0   XL    red  female  199.0   500.0    yes
 1    L  green    male   89.0   450.0     no
 2    M   blue  female   89.0   300.0    yes
 3    M  green  female  129.0   430.0     no
 4    M    red  female   79.0   410.0    yes
 5    M  green    male   89.0   430.0     no,
 np.True_)

In [ ]:
df=df_raw.copy()

In [ ]:
from sklearn.impute import SimpleImputer
simple_imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
simple_imputer.fit_transform(df[['price']])

array([[199.],
       [ 89.],
       [117.],
       [129.],
       [ 79.],
       [ 89.]])

In [ ]:
simple_imputer.statistics_

array([117.])

In [ ]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit_transform(df[['price','weight']])

array([[199., 500.],
       [ 89., 450.],
       [117., 300.],
       [129., 415.],
       [ 79., 410.],
       [ 89., 415.]])

In [ ]:
imputer.statistics_

array([117., 415.])

In [ ]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='median')
imputer.fit(df[['price','weight']])

SimpleImputer(strategy='median')

In [ ]:
imputer.statistics_

array([ 89., 430.])

In [ ]:
imputer=SimpleImputer(missing_values=np.nan,strategy='constant',fill_value=99.0)
imputer.fit(df[['price','weight']])

SimpleImputer(fill_value=99.0, strategy='constant')

In [ ]:
df.select_dtypes('object')

size  color  gender bought
0   XL    red  female    yes
1    L  green    male     no
2    M   blue     NaN    yes
3  NaN  green  female     no
4    M    red  female    yes
5    M  green    male     no

In [ ]:
imputer_objects=SimpleImputer(missing_values=np.nan,strategy='most_frequent')
imputer_objects.fit(df.select_dtypes('object').drop(columns='bought',axis=1))

SimpleImputer(strategy='most_frequent')

In [ ]:
imputer_objects.statistics_

array(['M', 'green', 'female'], dtype=object)

In [ ]:
df=df_raw.copy()

In [ ]:
pd.isnull(df)

size  color  gender  price  weight  bought
0  False  False   False  False   False   False
1  False  False   False  False   False   False
2  False  False    True   True   False   False
3   True  False   False  False    True   False
4  False  False   False  False   False   False
5  False  False   False  False    True   False

In [ ]:
pd.isnull(df['size'])

0    False
1    False
2    False
3     True
4    False
5    False
Name: size, dtype: bool

In [ ]:
pd.isnull(df.select_dtypes('number'))

price  weight
0  False   False
1  False   False
2   True   False
3  False    True
4  False   False
5  False    True

In [ ]:
pd.isnull(df.select_dtypes('object'))

size  color  gender  bought
0  False  False   False   False
1  False  False   False   False
2  False  False    True   False
3   True  False   False   False
4  False  False   False   False
5  False  False   False   False

In [ ]:
df[~pd.isnull(df['size'])]

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue     NaN    NaN   300.0    yes
4    M    red  female   79.0   410.0    yes
5    M  green    male   89.0     NaN     no

In [ ]:
df[~pd.isnull(df)]#nie działa

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue     NaN    NaN   300.0    yes
3  NaN  green  female  129.0     NaN     no
4    M    red  female   79.0   410.0    yes
5    M  green    male   89.0     NaN     no

In [ ]:
pd.isnull(df.select_dtypes('object'))

size  color  gender  bought
0  False  False   False   False
1  False  False   False   False
2  False  False    True   False
3   True  False   False   False
4  False  False   False   False
5  False  False   False   False

In [ ]:
df[~pd.isnull(df['weight'])]

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue     NaN    NaN   300.0    yes
4    M    red  female   79.0   410.0    yes

In [ ]:
df[pd.notnull(df['weight'])]

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue     NaN    NaN   300.0    yes
4    M    red  female   79.0   410.0    yes

In [ ]:
df[~pd.notnull(df['weight'])]

size  color  gender  price  weight bought
3  NaN  green  female  129.0     NaN     no
5    M  green    male   89.0     NaN     no

In [ ]:
df.select_dtypes('object').fillna('brak')

size  color  gender bought
0    XL    red  female    yes
1     L  green    male     no
2     M   blue    brak    yes
3  brak  green  female     no
4     M    red  female    yes
5     M  green    male     no

In [ ]:
df['size'].fillna(value='L',inplace=True)

/tmp/ipython-input-1322059667.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['size'].fillna(value='L',inplace=True)


In [ ]:
df=df.dropna()

In [ ]:
df

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
4    M    red  female   79.0   410.0    yes